module.exports = {
  tours: [
    {
      _id: '1',
      name: 'Discover the historic center',
      location: "CDMX",
      category: 'Culture',
      image: '../assets/img/items/bellas-artes.jpg',
      price: "500",
      brand: '-',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
      about : "Get to know the history of many of the most famous places such as the Palacio de Bellas Artes, Zocalo, Chinatown, and the cathedral, but we will also visit less touristy spots like old colonial houses and traditional candy stores, and get to know traditions that are still alive today. Plus, a perfect snack-stop and many, many fun facts."
    },
        {
      _id: '2',
      name: 'Teotihuacan Ballon Ride',
      location: "CDMX",
      category: 'Culture',
      image: 'https://ichef.bbci.co.uk/news/800/cpsprodpb/BEE3/production/_118676884_gettyimages-73656849.jpg.webp',
      price: "3000",
      brand: '-',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
      about : "This experience is your great opportunity to get to know Teotihuacan from another perspective, out of the ordinary. Fly in a balloon and let the wind take you on an unforgettable journey, witnessing the first contact between man and heaven."
    },
    {
      _id: '3',
      name: 'Chichen Itza, Cenote and Valladolid',
      location: "Riviera Maya",
      category: 'Culture',
      image: 'https://www.mexicodesconocido.com.mx/wp-content/uploads/2010/05/chichen-itza-arquitectura-que-visitar.png',
      price: "1,190"
      ,
      brand: '-',
      rating: 5,
      numReviews: 51,
      about : "I will take you to explore one of the seven wonders of the modern world Chichen Itza in a unique experience. Before we will pass to the center of Valladolid and after knowing the archeological site I will take you to know an authentic Mayan cenote, beauty of nature full of mysticism. At noon you will enjoy a delicious buffet of regional Mexican food with vegetarian options. /n   Once in Chichen Itza, we will walk through the observatory, the Temple of the Warriors and the Ball Court. And you will see the legendary Kukulkan Pyramid, also known as El Castillo, from the front, and I will tell you how during the equinox on a clear day, a snake slides down the stairs of the pyramid, which is actually a shadow created by the setting sun . You will live closely the mysteries of acoustics in its architecture, which to date are not fully understood. You will clearly hear a whisper 159 feet (46 meters) away on one of the platforms on the colossal ball court where the Maya played sports. /n With this exclusive tour, your visit to Chichen Itza allows you to explore the archeological site in an exclusive and unique way!"
    },
    {
      _id: '4',
      name: 'Magic CENOTES + Hacienda',
      location: "Riviera Maya",
      category: 'Recreative',
      image: '../assets/img/items/cenote.jpg',
      price: "990",
      brand: '-',
      rating: 4,
      numReviews: 45,
      about : "This is an authentic Yucatecan experience. We'll visit 2 of our favorite cenotes and one hacienda (historical building) on ​​this day of Mayan jungle adventure & probably (hopefully) we'll have them just to ourselves (depending on the season and the day) or at least we won't find a crowd in them. (Perfect for families, couples, groups of friends, and solo travelers). The first cenote is a cavern one, with sapphire blue water (not cold) from where we will appreciate to the bottom of it (it may vary in raining season). The second cenote is a perfectly shaped open circle with incredible emerald water surrounded by trees and birds.       We’ll tell you a few things about the mayan culture as you take in the impressive views of these hundreds of millions of year old rock formation while you swim, snorkel, explore, float, do high jumps from almost 32 ft! (just for the most adventurous) or just relax in each of these cold&fresh water cenotes taking pictures. We will stay from 45 mins to 1 hour (depending on you) in each cenote, without rushing (something typical in normal tours).        Finally, you will enjoy a regional artisanal organic firewood cooked meal prepared by the Mayan community from the harvest to your plate (welcome to México!) for less than the cost of a beer in california! (Not included in the price)"
    },
    {
      _id: '5',
      name: 'Mezcal tasting & dinner in mini jungle',
      location: 'Riviera Maya',
      category: 'Nightlife',
      image: "../assets/img/items/mezcal.webp",
      price: "2,200",
      brand: '-',
      rating: 2.5,
      numReviews: 198,
      countInStock: 6,
      about : "Join us for an intimate dinner party & mezcal tasting in our private jungle garden in the center of Tulum Pueblo! Everyone is welcome to our garden where we will prepare a 3-course dinner cooked on the fire paired with 1.5 ounce tastings of five artisanal, small-batch mezcals sourced from different regions around the country. We create a new dinner menu for every tasting based on any allergies or dietary restrictions. This experience is best for adventurous eaters as we do not disclose the menu beforehand. For an idea of what we typically serve, refer to our photos! Throughout the dinner, we will talk a little bit about the differences between mezcal and tequila, the process of producing mezcal, what to look for when purchasing mezcal & why it has become so popular in the past few years. Most importantly, we’ll have a good time sharing food & drinks, and creating new experiences with great people."
    },
    {
      _id: '6',
      name: 'Knowing Tlaquepaque',
      location: 'Jalisco',
      category: 'Culture',
      image: '../assets/img/items/tlaquepaque.jpg',
      price: "900",
      brand: '-',
      rating: 3.5,
      numReviews: 89,
      countInStock: 6,
      about :"One of the Mexican cities with the greatest artisan tradition, but above all a place where the secrets of artisanal techniques in ceramics and pottery are amalgamated in beautiful and innovative decorative handicraft pieces worthy of admiration.<br>Its charming gastronomy, seasoned with the warmth of home and also its high cuisine that the different places have will give you a fantastic experience.<br>It has beautiful tourist attractions that will lead you to discover something more than the showcases of fine crafts that we are sure you will love."
    },
    {
      _id: '7',
      name: 'Visiting the 9 esquinas',
      location: 'Jalisco',
      category: 'Gastronomic',
      image: '../assets/img/items/9-esquinas.jpg',
      price: "600",
      brand: '-',
      rating: 4.5,
      numReviews: 45,
      countInStock: 6,
      about: 'Las Nueve Esquinas is one of the most popular and traditional places in the Historic Center of Guadalajara, famous for its beautiful square, its delicious birrias, and its printing area. In May , we can buy Pitayas around the square which is a fruit coming from different cactus species and is very tasty, has many different colors and is very tasty. If we talk about desserts we can find Nieve de garrafa and Tejuino which for sure would be pleasing for everyone.',
    },
    {
      _id: '8',
      name: 'Lucha libre night',
      location: 'CDMX',
      category: 'Nightlife',
      image: '../assets/img/items/lucha.jpg',
      price: "1,200",
      brand: '-',
      rating: 4.5,
      numReviews: 45,
      countInStock: 6,
      about: 'We will start by tasting mouth watering tacos in one of our favorite  taquerias, then we will go have some beer and mezcal or pulque. While we wash down the tacos, we will introduce you to the history and nuances of lucha libre—professional Mexican wrestling. We will then head to the arena for a fantastic night of lucha libre! Other things to note Tickets, food, and drinks before the show are included — all you need to do is enjoy.',
    },
    {
      _id: '9',
      name: 'Botanical tour in the middle of the city',
      location: 'CDMX',
      category: 'Cultural',
      image: 'https://upload.wikimedia.org/wikipedia/commons/0/07/Invernadero_de_pinos_en_Xochimilco.JPG',
      price: "1,100",
      brand: '-',
      rating: 4.8,
      numReviews: 31,
      countInStock: 6,
      about: 'Medicinal herbs, edible trees, magic flowers. Between the streets and the asphalt there are hidden different species of plants that we will learn to identify on a tour of one of the most beautiful areas of the city. We will talk about its different uses and history so that we can feel connected with nature and take that curiosity back home to appreciate those life companions to whom we do not often pay attention: plants.',
    },
    {
      _id: '10',
      name: 'Eat street food & exotic fruits at Sunday Market in the city',
      location: 'CDMX',
      category: 'Gastronomic',
      image: 'https://escuanto.mx/wp-content/uploads/2020/03/locatarios-mercados-cdmx-apoyados-seguro-850x560.jpg',
      price: "600",
      brand: '-',
      rating: 4.3,
      numReviews: 11,
      countInStock: 6,
      about: 'Let’s have a chill walk through Reforma, enjoying the sunday afternoon, on our way to the market. We will explore a Tianguis (street market) and eat our way around the best eats in the city. We will eat cochinita tacos, tlacoyos, quesdillas, birria, pozole, we will try snacks, and aguas frescas. Whatever catches our eye, we can try. We will also try local fruits that can only be found in this part of the world such as mamey, sapote negro, chico, tuna fruit Just a little bit of evrything so you can experience a full day of mexican cuisine all at once.',
    },
    {
      _id: '11',
      name: 'Mexico through the centuries',
      location: 'CDMX',
      category: 'Cultural',
      image: 'https://upload.wikimedia.org/wikipedia/commons/5/5c/PLAZA_DE_LAS_TRES_CULTURAS-1.jpg',
      price: "800",
      brand: '-',
      rating: 4.9,
      numReviews: 234,
      countInStock: 6,
      about: 'With this walking tour, we get to discover Mexico history and art in all its glory and throughout different eras: the ancient, colonial and contemporary. We will stroll among Mexico City most important streets, then and now, and get a glimpse of daily life and the people of Mexico City.',
    }
  ],
}